module.exports = {
	appName: 'OverwatchInfi',
	home: 'Home',
	heros: 'Heros',
	news: 'News',
	twits: 'Twitter',
    video: 'Video',
	about: 'About',
	pro: 'Pro',
	youtube: 'Youtube',
	gfycat: 'Gfycat',
	account: 'Account',
	login: 'Login',
	signup: 'Sign up',
	guide: 'Guide',
	buildGuide: 'Build your own guide combination',
	loginToBuildGuid: 'Login to build your own guide combination',
	mapSelection: 'Please select one of the maps on the left side',
	next: 'Next',
	cancel: 'Cancel',
	finish: 'Finish',
	selectMap: 'Select Map',
	selectHero: 'Select Hero',
	titleComment: 'Title and Comment',
	previous: 'previous',
	offense: 'Offense',
	defense: 'Defense',
	guideBuildSuccess: 'Successfully submitted your combination!',
	guideBuildFail: 'Server is busy please try again later :-(',
	guideInputHint: 'Title and description can not be empty',
	loginSuccess: 'You have successfully login!',
	loginError: 'Wrong username or password, please try again',
	chooseSide: 'Please choose the side of the team',
	chooseTeam: 'Choose 6 heros from left to build your team',
	latestVideo: 'Latest Videos',
	latestNews: 'Latest News',
	teamGuide: 'Team Guide',
	battleTag: 'Please type in your battle tag',
	region: 'Region',
	platform: 'Platform',
	noMatchFound: 'Found no user with the battletag, please try another one',
	searchError: 'An error happened during the search, please try again'
};